# Generated by Django 3.0.3 on 2022-09-05 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0008_remove_learnpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='learn_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
