# Generated by Django 3.0.3 on 2022-09-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_learnpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
    ]
